1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np
import random
arr=np.random.randint(1,101,(3,3))
print(f"orginal array\n{arr}")
print(f"Transpose array\n{arr.T}")

orginal array
[[47 49 28]
 [40 53 44]
 [63 94 92]]
Transpose array
[[47 40 63]
 [49 53 94]
 [28 44 92]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [3]:
arr1=np.random.randint(1,21,size=10)
print(f"orginal array\n{arr1}")
print(f"reshaped to 2*5\n{np.reshape(arr1,(2,5))}")
print(f"reshaped to 5*2\n{np.reshape(arr1,(5,2))}")



orginal array
[16 12 15  2  6 14 19 14 15  1]
reshaped to 2*5
[[16 12 15  2  6]
 [14 19 14 15  1]]
reshaped to 5*2
[[16 12]
 [15  2]
 [ 6 14]
 [19 14]
 [15  1]]


3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [4]:
arr3=np.random.uniform(1,4,(4,4))
arr4=np.array([0,0,0,0])
arr5=np.reshape(arr4,(4,1))
arr6=[0,0,0,0,0,0]
ans_hori=np.hstack((np.hstack((arr5,arr3)),arr5))
ans=np.vstack((np.vstack((arr6,ans_hori)),arr6))
print(ans)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         3.84056287 3.76072116 1.63227529 2.29707688 0.        ]
 [0.         1.82954334 2.09974285 3.8792809  2.2510328  0.        ]
 [0.         2.08273407 2.79888788 1.39320991 2.82363548 0.        ]
 [0.         3.2024487  1.66484458 1.37437018 2.24237236 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [5]:
arr7 = np.arange(10, 61, 5)
print(f"array of integers from 10 to 60\n{arr7}")

array of integers from 10 to 60
[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [6]:
arr8=np.array(['python', 'numpy', 'pandas'])
print(f"uppercase \n{np.char.upper(arr8)}")
print(f"lowercase \n{np.char.lower(arr8)}")
print(f"titlecase \n{np.char.title(arr8)}")
print(f"captitalize case \n{np.char.capitalize(arr8)}")

uppercase 
['PYTHON' 'NUMPY' 'PANDAS']
lowercase 
['python' 'numpy' 'pandas']
titlecase 
['Python' 'Numpy' 'Pandas']
captitalize case 
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [9]:
def insert_spaces(word):
    return ' '.join(word)
vectorized_insert_spaces = np.vectorize(insert_spaces)
spaced_array = vectorized_insert_spaces(arr8)
print(f"Array with spaces between characters:\n{spaced_array}")


Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [10]:
import numpy as np

arr_1=np.array([[1,2,3],[4,5,6]])
arr_2=np.array([[7,8,9],[10,11,12]])
print(f"array1\n{arr_1}")
print(f"array2\n{arr_2}")
print(f"addition\n{arr_2+arr_1}")
print(f"substraction\n{arr_2-arr_1}")
print(f"multiplication\n{arr_2*arr_1}")
print(f"division\n{arr_2/arr_1}")

array1
[[1 2 3]
 [4 5 6]]
array2
[[ 7  8  9]
 [10 11 12]]
addition
[[ 8 10 12]
 [14 16 18]]
substraction
[[6 6 6]
 [6 6 6]]
multiplication
[[ 7 16 27]
 [40 55 72]]
division
[[7.  4.  3. ]
 [2.5 2.2 2. ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [11]:
import numpy as np
arr_4=np.eye(5)
elements=np.diag(arr_4)
print(f"diagnaol elements are{elements}")

diagnaol elements are[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [12]:
import numpy as np
import random
def prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True
arr=np.random.randint(1,1001,size=100)
primes=[x for x in arr if prime(x)]
print(f"given array\n {arr}")
print(f"primes are \n{primes}")


    

given array
 [183 296 111 788 618 722 132  31 770 418 173 265 642   5 353 975 566 186
 306 401 953 533 886 350 100 814 342 926 806 928 851 444 596 995 946 393
 979  49 479 809 156 485 344 755 792 508 522 338 928 585 338 174 260 724
 949 615 227 814 394 888 740 984 411 982 285 428 358 464 320 437 912 374
 807 762 647 772 875  47 344 972 960  44 179  17 621 577 849 701 106 431
  69 709 574 733 107 613 463 356 887 477]
primes are 
[31, 173, 5, 353, 401, 953, 479, 809, 227, 647, 47, 179, 17, 577, 701, 431, 709, 733, 107, 613, 463, 887]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [13]:
daily_temp = np.random.randint(10, 30, size=28)  
weekly_temp = np.array_split(daily_temp, 4)
for i in range(len(weekly_temp)):
    print(f"{i+1} week average is {np.mean(weekly_temp[i])}")


1 week average is 18.428571428571427
2 week average is 18.428571428571427
3 week average is 15.714285714285714
4 week average is 22.0
