2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In [2]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,1])

print("mean",np.mean(a1))
print("avereage",np.average(a1))
print("weighted average",np.average(a1,weights=a2))



mean 2.5
avereage 2.5
weighted average 2.5714285714285716


3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [3]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

print("2D array\n",arr2)

[1 2 3 4 5]
2D array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print("array reversing using slicing")
print("1D Array reversing\n",arr1[::-1])
print("2D array reversing in rows\n",arr2[::-1,:])
print("2D array reversing in columns\n",arr2[:,::-1])
print("2D array reversing \n",arr2[::-1,::-1])




array reversing using slicing
1D Array reversing
 [5 4 3 2 1]
2D array reversing in rows
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
2D array reversing in columns
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
2D array reversing 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [8]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print("1d\n",np.flip(arr1))
print("2d\n",np.flip(arr2))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
1d
 [5 4 3 2 1]
2d
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In [11]:
k=np.array([1,2,3,4])
print(k.dtype)

int64


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In [12]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(f"using hstack()\n{np.hstack((arr1,arr2))}")
print(f"using vstack()\n{np.vstack((arr1,arr2))}")

using hstack()
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
using vstack()
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In [13]:
arr_1d = np.array([1, 2, 3])
print(f"fliplr passing array as 2D \n{np.fliplr([arr_1d])}")  
print(f"flipud \n{np.flipud(arr_1d)}")    

fliplr passing array as 2D 
[[3 2 1]]
flipud 
[3 2 1]


In [14]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(f"fliplr \n{np.fliplr(arr_2d)}")
print(f"flipud \n{np.flipud(arr_2d)}")

fliplr 
[[3 2 1]
 [6 5 4]]
flipud 
[[4 5 6]
 [1 2 3]]


In [15]:
arr_3d=np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]]])
print(f"fliplr \n{np.fliplr(arr_3d)}")
print(f"flipud \n{np.flipud(arr_3d)}")

fliplr 
[[[ 7  8  9]
  [ 4  5  6]
  [ 1  2  3]]

 [[16 17 18]
  [13 14 15]
  [10 11 12]]]
flipud 
[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(f"split using sections \n{np.array_split(arr, 3)}")
print(f"split using index \n{np.array_split(arr, [2,5])}")


split using sections 
[array([1, 2, 3]), array([4, 5]), array([6, 7])]
split using index 
[array([1, 2]), array([3, 4, 5]), array([6, 7])]


In [17]:
arr = np.array([[1, 2, 3, 4] ,[5, 6, 7,8],[9,10,11,12],[13,3,4,5],[1,44,21,4]])
print("split along coulmns")
print(f"split using sections\n{np.array_split(arr, 2,axis=1)}")
print(f"split using index \n{np.array_split(arr, [1,3],axis=1)}")
print("split along rows")
print(f"split using sections\n{np.array_split(arr, 2,axis=0)}")
print(f"split using index \n{np.array_split(arr, [1,3],axis=0)}")



split along coulmns
split using sections
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13,  3],
       [ 1, 44]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [ 4,  5],
       [21,  4]])]
split using index 
[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [ 1]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [ 3,  4],
       [44, 21]]), array([[ 4],
       [ 8],
       [12],
       [ 5],
       [ 4]])]
split along rows
split using sections
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13,  3,  4,  5],
       [ 1, 44, 21,  4]])]
split using index 
[array([[1, 2, 3, 4]]), array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13,  3,  4,  5],
       [ 1, 44, 21,  4]])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

In [18]:
#broadcasting
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([1,0,-1])
ans = a1 + a2
print(ans)


[[2 2 2]
 [5 5 5]
 [8 8 8]]


In [19]:
#vectorization
print(f"multpying a1 by 2 \n{a1*2}")

multpying a1 by 2 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
